# Uncomment this line to define a global platform for your project
# platform :ios, "7.0"

target "LocationsApp" do

pod 'MCSwipeTableViewCell', '~> 2.1'
pod 'LayerKit'

end

target "LocationsAppTests" do

end

